

services:
  django:
    build: .
    container_name: django
    command: sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - bd
    environment:
      - DEBUG=True

  bd:
    image: postgres
    container_name: bd
    env_file:
      - .env
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - "5434:5432"

  redis:
    image: redis:latest
    restart: on-failure
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    command: celery -A config worker -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - django
      - bd

  celery-beat:
    build: .
    volumes:
      - .:/usr/src/app/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    restart: on-failure
    depends_on:
      - redis
      - django
    command: celery -A config beat -l INFO

volumes:
  pgdbdata: