# Generated by Django 5.0.7 on 2024-07-10 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course_previews/', verbose_name='изображение курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание курса')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='название урока')),
                ('lesson_description', models.TextField(blank=True, null=True, verbose_name='описание урока')),
                ('lesson_preview', models.ImageField(blank=True, null=True, upload_to='lesson_previews/', verbose_name='изображение урока')),
                ('lesson_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='ссылка на видео')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец урока')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
