# Generated by Django 5.0.7 on 2024-07-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/course_previews/', verbose_name='изображение курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/lesson_previews/', verbose_name='изображение урока'),
        ),
    ]
